language: node_js
cache: npm
node_js:
- '10.14'
os:
- windows
- osx
- linux
script:
- npm run test
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm run build-win; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build-mac; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build-linux; fi
after_script:
- ls -R dist
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then tar -zcf ${TRAVIS_BUILD_DIR}/mob-timer-win32-x64-${TRAVIS_TAG}-${TRAVIS_COMMIT}.tar.gz
  dist/mob-timer-win32-x64; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-mac; cp ./dist/mob-timer-darwin-x64/mob-timer.dmg
  ${TRAVIS_BUILD_DIR}/mob-timer-darwin-x64-${TRAVIS_TAG}-${TRAVIS_COMMIT}.dmg; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -zcf ${TRAVIS_BUILD_DIR}/mob-timer-linux-x64-${TRAVIS_TAG}-${TRAVIS_COMMIT}.tar.gz
  dist/mob-timer-linux-x64; fi
deploy:
  provider: releases
  api_key:
    secure: R/c9PX9amrZ0v8jMtrbOjBD7JKlzhUUfK89l6jXdeQgw+blZKrPpi3RrgOaGNSdEWULJFqbTDN4OA2ttSSf4sWlgwzUrJDwfvKNCAjPbgFaswSUfhqZQuiqbnlNTvZ67K4myFU8AXOCwSVQXMB06B+/ZaRMhxhIlT56PkNFPFnw/8zya3EFhjK1B5wVV+qgzDbPYWHvlU1jbBOvYfTePSgIVai6dKTiuMRB4D5tSe2tCbBG/J8NqllV+SiOzwjEOpoH1fOSeADUIfQJ9w3cZ26WqFDbAoqVH2Qz//I8lp9aRA2C/RkZKCLKQiMjhMQqLasnxne3xp/hISqY0NZHDKP/Qj5JjZiDhuibc1O4S/0yQVqKhcCaB9jPRLcRZUq79IboTX/EAE6wfW3ZHqC9oWGzxAWknl6r3rwIYqQqMFJKtm7jEL4BGae9ynR8Req235EPxbxrU1YE5EvdzwvwAofTdfZKK9zZeejNdVyCTMK0JBCra7k14cUKxiMrJ3LrqEaILwCIrbkSWh2lLDwzgN13FcF1uHjwryRm+mBcyV/nTyxoAoWcRqFuOwbL/gfe+B/+3AMTvhYATlEd4ujjLHrzK4sB6R31qvdPmEa+5wePR348nmHq/cVOPx6UC0cDJzPSuW2n90Bx11KW45fnMeReEx+q+GQpJ4NoZeJIh5VU=
  file:
  - "${TRAVIS_BUILD_DIR}/mob-timer-win32-x64-${TRAVIS_TAG}-${TRAVIS_COMMIT}.tar.gz"
  - "${TRAVIS_BUILD_DIR}/mob-timer-darwin-x64-${TRAVIS_TAG}-${TRAVIS_COMMIT}.dmg"
  - "${TRAVIS_BUILD_DIR}/mob-timer-linux-x64-${TRAVIS_TAG}-${TRAVIS_COMMIT}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
